import json
import os
import time
from google import genai
from google.genai import types, errors

# ---------------------------------------------------------
# SETUP
# ---------------------------------------------------------
# Best Practice: Load from environment variable
# os.environ["GEMINI_API_KEY"] = "Paste_New_Key_Here"
client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

# ---------------------------------------------------------
# HELPER FUNCTIONS
# ---------------------------------------------------------
def generate_table_documentation(table_name, columns):
    prompt = f"""
    You are a Technical Writer documenting a SQL Server database.
    
    Current Table: {table_name}
    Schema Definition:
    {json.dumps(columns, indent=2)}
    
    Task:
    1. Write a 1-sentence description of the table.
    2. Create a Markdown table listing the columns.
    3. For each column, provide a 'Description' field inferred from the name.
    
    Output strictly in Markdown format.
    """

    # RETRY LOGIC
    # We try up to 3 times for a single table if we get rate limited.
    max_retries = 3
    retry_delay = 30  # Seconds to wait if we hit a 429 error

    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model="gemini-2.0-flash",
                contents=prompt,
                config=types.GenerateContentConfig(
                    system_instruction="You are a helpful database documentation assistant.",
                    temperature=0.1
                )
            )
            return response.text

        except errors.ClientError as e:
            # Check if it is a Rate Limit error (429)
            if e.code == 429:
                print(f"⚠️ Quota hit for '{table_name}'. Cooling down for {retry_delay}s... (Attempt {attempt+1}/{max_retries})")
                time.sleep(retry_delay)
                # After sleeping, the loop continues and retries the call
            else:
                # If it's a different error (e.g., 400 Bad Request), raise it
                print(f"❌ API Error for '{table_name}': {e}")
                return f"Error documenting {table_name}: {e.message}"
    
    return f"Failed to document {table_name} after rate limit retries."

# ---------------------------------------------------------
# MAIN EXECUTION
# ---------------------------------------------------------
def main():
    schema_path = os.path.join(os.path.dirname(__file__), 'db_schema.json')
    output_path = os.path.join(os.path.dirname(__file__), 'Technical_Docs.md')

    # Load Schema
    try:
        with open(schema_path, 'r') as f:
            schema = json.load(f)
    except FileNotFoundError:
        print("Error: db_schema.json not found.")
        return

    # Initialize file with header (Overwrite mode 'w')
    with open(output_path, 'w') as f:
        f.write("# Database Documentation\n\n_Auto-generated by Gemini_\n\n")

    print(f"Starting documentation for {len(schema)} tables...")

    for table_name, columns in schema.items():
        print(f"📄 Processing: {table_name}...")
        
        # 1. Generate Doc
        doc_segment = generate_table_documentation(table_name, columns)
        
        # 2. Append immediately to file (Safety mechanism)
        # We use 'a' (append) mode so we don't lose progress if script crashes later
        with open(output_path, 'a') as f:
            f.write(f"## Table: {table_name}\n\n")
            f.write(doc_segment + "\n\n---\n\n")

        # 3. Smart Rate Limiting
        # The Free Tier allows ~15 requests per minute.
        # 60s / 15 reqs = 4 seconds per request.
        # We sleep 5 seconds to be safe.
        print("   ...Done. Sleeping 5s.")
        time.sleep(5) 

    print(f"✅ Full documentation saved to {output_path}")

if __name__ == "__main__":
    main()